# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

basic_logistic_reg_ <- function(x, y) {
    .Call(`_LRpadding_basic_logistic_reg_`, x, y)
}

logistic_reg_ <- function(x, y, start, eps_f, eps_g, maxit) {
    .Call(`_LRpadding_logistic_reg_`, x, y, start, eps_f, eps_g, maxit)
}

basic_padding_logistic_reg_ <- function(x, y, padding = 0L) {
    .Call(`_LRpadding_basic_padding_logistic_reg_`, x, y, padding)
}

padded_logistic_reg_ <- function(x, y, padding, start, eps_f, eps_g, maxit) {
    .Call(`_LRpadding_padded_logistic_reg_`, x, y, padding, start, eps_f, eps_g, maxit)
}

