# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

logistic_reg_ <- function(x, y) {
    .Call(`_LRpadding_logistic_reg_`, x, y)
}

padding_logistic_reg_ <- function(x, y, padding = 0L) {
    .Call(`_LRpadding_padding_logistic_reg_`, x, y, padding)
}

